# Generated by Django 4.2.3 on 2023-07-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_usergooglecredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergooglecredentials',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergooglecredentials',
            name='scopes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
