# Generated by Django 4.2.3 on 2023-07-19 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0004_alter_usergooglecredentials_access_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergooglecredentials',
            options={'verbose_name': 'User Account Credentials', 'verbose_name_plural': 'User Account Credentials'},
        ),
        migrations.AddField(
            model_name='usergooglecredentials',
            name='account_type',
            field=models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft')], default='google', max_length=100),
        ),
        migrations.AlterField(
            model_name='usergooglecredentials',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
