# Generated by Django 4.2.3 on 2023-07-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_externalcalendarevent_html_link_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcalendarevent',
            name='calendar_type',
            field=models.CharField(choices=[('google_calendar', 'Google Calendar'), ('microsoft_calendar', 'Microsoft Calendar')], default='google_calendar', max_length=100),
        ),
        migrations.AddField(
            model_name='externalcalendarevent',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
