# Generated by Django 4.2.3 on 2023-07-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_remove_location_state_remove_location_zip_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='end_date',
        ),
    ]
